In [2]:
from sklearn.datasets import load_iris
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
import numpy as np


np.random.seed(0) #if we set the seed() every time when we call numpy's other random module-func we get same o/p


### Step1 - exploring the dataset

In [7]:
iris = load_iris()

df = pd.DataFrame(iris.data, columns = iris.feature_names)

df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [16]:
response = list(iris.target)
df['species'] = response
df.head()

# we can use the above method but it gives target var. names in codes0,1,2 for readability we want it in words
# if we use target_names in place of it ,it will not work since have only 3 items in it and can't assign those to many rows

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   species  
0        0  
1        0  
2        0  
3        0  
4        0

In [18]:
# we are using categorical.from_codes(code,word associated with code) method to break down each code with its word form
df['species'] = pd.Categorical.from_codes(iris.target,iris.target_names)

df.head()


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [30]:
response = list(iris.target)
df['species_code'] = response
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  species_code  
0  setosa             0  
1  setosa             0  
2  setosa             0  
3  setosa             0  
4  setosa             0

In [33]:
x = df.iloc[:,0:4]
y = df.iloc[:,5]


0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: species_code, Length: 150, dtype: int64

### Step2 - splitting for training and testing

In [34]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25, random_state = 0)

In [35]:
print(len(x_train))
print(len(y_train))
print(len(x_test))
print(len(y_test))

112
112
38
38


### Step3 - creating the model 

In [36]:
clf = RandomForestClassifier(n_jobs = 2, random_state = 0) #thru the n_jobs we are telling the no. of jobs to run in parallel 
#by default it uses the 'gini' method to construct the decision tree rather than entropy
# random_state controls the randomness of bootstrapping

clf.fit(x_train,y_train)
# here it creates many decision tree i.e 100 decision trees and by fitting our data by using bootstrapping ensemble method.

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

### Step4 - Testing the model and checking its accuracy 

In [47]:
print(clf.predict(x_test))
y_pred = clf.predict(x_test)
#here we are passing the x_test dataset to all 100 decision tree and try to get its o/p

print(clf.predict_proba(x_test))
#it predicts the probability of answer of each x_test val
#in 1st case prob. of flower=2 is high so predicts 2 i.e after passing x_test to 100 diff dec. trees majority of them returns it as 2
#similarly in 2nd case majority returns flower=1 and so on..

print(iris.target_names[clf.predict(x_test)])
#printing the above names

[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]
[[0.   0.01 0.99]
 [0.   0.94 0.06]
 [1.   0.   0.  ]
 [0.   0.   1.  ]
 [1.   0.   0.  ]
 [0.   0.01 0.99]
 [1.   0.   0.  ]
 [0.   0.99 0.01]
 [0.   0.92 0.08]
 [0.   1.   0.  ]
 [0.   0.24 0.76]
 [0.   0.99 0.01]
 [0.   0.99 0.01]
 [0.   0.94 0.06]
 [0.   0.99 0.01]
 [1.   0.   0.  ]
 [0.   0.95 0.05]
 [0.   0.97 0.03]
 [1.   0.   0.  ]
 [1.   0.   0.  ]
 [0.   0.27 0.73]
 [0.   0.92 0.08]
 [1.   0.   0.  ]
 [1.   0.   0.  ]
 [0.   0.22 0.78]
 [1.   0.   0.  ]
 [1.   0.   0.  ]
 [0.   1.   0.  ]
 [0.   0.95 0.05]
 [1.   0.   0.  ]
 [0.   0.01 0.99]
 [0.05 0.8  0.15]
 [1.   0.   0.  ]
 [0.   0.2  0.8 ]
 [0.   0.   1.  ]
 [0.   0.97 0.03]
 [1.   0.   0.  ]
 [0.   0.12 0.88]]
['virginica' 'versicolor' 'setosa' 'virginica' 'setosa' 'virginica'
 'setosa' 'versicolor' 'versicolor' 'versicolor' 'virginica' 'versicolor'
 'versicolor' 'versicolor' 'versicolor' 'setosa' 'versicolor' 'versicolor'
 'setosa' 'setosa' 

In [48]:
#prints 1st 5 elem. of actual y val.
print(y_test.head())


114    2
62     1
33     0
107    2
7      0
Name: species_code, dtype: int64


In [50]:
#printing the confusion matrix
import seaborn as sns
from sklearn import metrics

#printing confusion matrix using nomal array notation
print(metrics.confusion_matrix(y_test,y_pred))

#printing confusion matrix using pandas datafame
pd.crosstab(y_test,y_pred, rownames=['Actual Spieces'], colnames=['Predicted Species'])



[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


Predicted Species   0   1  2
Actual Spieces              
0                  13   0  0
1                   0  15  1
2                   0   0  9

In [52]:
#printing the accuracy of model
print(metrics.accuracy_score(y_test,y_pred)*100,'%')

97.36842105263158 %
